### ISSUE TITLE
Why num_vocab = 512?

### ISSUE THREAD

**Issue by MarcoTurzi** [teddykoker/image-gpt#24]
I know it could sound stupid but I was wondering why did you decided to use 512 instead of 256, since usually images pixels are in a range [0,255].

**Comment by teddykoker** [comment]
Hi @MarcoTurzi, good question! This is how it is done in the [original paper](https://cdn.openai.com/papers/Generative_Pretraining_from_Pixels_V2.pdf) (section 3.2):

> Instead, motivated by early color display palettes, we create our own 9-bit color palette by clustering (R, G, B) pixel values using k-means with k = 512. 

Since images are 3 channels (R, G, B) to represent the full range you would need a vocabulary of size $256^3$. Since not all of these colors occur with uniform distribution in natural images, you can reduce the space of the vocabulary through clustering, which creates a 9-bit palette.
