### ISSUE TITLE
[Question] Why do you transpose the input shape to (seq len, batch)?

### ISSUE THREAD

**Issue by GregorKobsik** [teddykoker/image-gpt#8]
Not an issue, just a question about design decisions of the model:

In the function `_to_sequence()` you transpose the batch and sequence length dimensions. Could you provide a rationale on this decision? 

I am wondering which advantages does this yield and why did you decide to put the batch dimension second in favor of the sequence length. I would naively assume that the batch size should be the first dimension, when defining a model.

https://github.com/teddykoker/image-gpt/blob/0d8a938b6e5b7a5ff6a0c5ab6348e6c7df48a48a/src/image_gpt.py#L14-L18

Sincerely, Gregor

P.S.

I figured out, that the PyTorch implementation of the [Transformer](https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html#torch.nn.Transformer) does also use sequences as the first dimension, similar to other modules heavily used in NLP, like GRUs or RNNs. Although the [Transformer Encoder](https://pytorch.org/docs/stable/generated/torch.nn.TransformerEncoder.html#torch.nn.TransformerEncoder) does not specify its shapes directly. 

If you could provide me with some explanation, that would be great, otherwise you can close the issue. 
I suppose it is a coding convention or style thing.

**Comment by teddykoker** [comment]
Hey Gregor! Thank you for your patience, I am just seeing this now. PyTorch's [implementation](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html) of MultiheadAttention also uses sequences as the first dimension (like the transformer implementation), so that is why I used the sequence length as the 1st dimension. I am not necessarily sure why this decision was made for the PyTorch implementation, and agree that it can be confusing. 

If you would prefer to use batch as the 1st first dimension there are a number of multihead attention implementations that could be used instead, see [karpathy/minGPT](https://github.com/karpathy/minGPT/blob/master/mingpt/model.py#L37-L79)
